footprint: [[0.31, 0.25],[0.31, -0.25],[-0.31, -0.25],[-0.31, 0.25],[0.31, 0.25]]
map_type: costmap

obstacle_layer:
  enabled: true
  max_obstacle_height: 3.0
  min_obstacle_height: 0.0
  obstacle_range: 5.0
  raytrace_range: 6.0
  inflation_radius: 0.1
  combination_method: 1
  observation_sources: scan
  track_unknown_space: true

  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: false
  footprint_clearing_enabled: true

  velodyne:
    data_type: PointCloud2
    topic: /velodyne_points
    marking: true
    clearing: true
    expected_update_rate: 0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.2
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.2

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.1  # 從 0.7 降到 0.5

static_layer:
  enabled: true
  map_topic: "/map"