local_costmap:
  global_frame: odom  # 從 map 改為 odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0  # 從 5.0 降到 2.0
  static_map: false
  rolling_window: true
  width: 6.0  # 從 4.0 改為 6.0
  height: 6.0  # 從 4.0 改為 6.0
  resolution: 0.1  # 從 0.05 改為 0.1
  transform_tolerance: 1.0
  map_type: costmap

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}  # 啟用
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}  # 啟用