shutdown_costmaps: false

controller_frequency: 10.0  # 從 20.0 降到 10.0
controller_patience: 5.0

planner_frequency: 0.5  # 從 5.0 降到 0.5
planner_patience: 15.0

oscillation_timeout: 10.0  # 從 0 改為 10.0
oscillation_distance: 0.2

# Planner selection
base_global_planner: "global_planner/GlobalPlanner"  
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

max_planning_retries: -1

recovery_behavior_enabled: true  # 從 false 改為 true
clearing_rotation_allowed: false

recovery_behaviors:
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'move_slow_and_clear'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 0.5  # 從 0.1 改為 0.5
  layer_names: [obstacle_layer]