footprint: [[0.31, 0.25],[0.31, -0.25],[-0.31, -0.25],[-0.31, 0.25],[0.31, 0.25]]  # 與 TEB 一致
map_type: costmap

obstacle_layer:
  enabled: true
  max_obstacle_height: 2.0  # 從 3.0 降到 2.0
  min_obstacle_height: 0.0  # 從 0.05 改為 0.2
  obstacle_range: 6.0  # 從 3.0 改為 5.0
  raytrace_min_range: 0.0
  raytrace_range: 6.0  # 從 3.5 改為 6.0
  inflation_radius: 0.3  # 從 0.8 改為 0.5
  combination_method: 1
  observation_sources: scan
  track_unknown_space: true

  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: false
  footprint_clearing_enabled: true
  # velodyne:
  #   data_type: PointCloud2
  #   topic: /velodyne_points
  #   marking: true
  #   clearing: true
  #   # expected_update_rate: 0
  #   max_obstacle_height: 20.0
  #   min_obstacle_height: 0.01
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0

inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 0.3  # 從 0.8 降到 0.5
  inflate_unknown: true

static_layer:
  enabled: true
  map_topic: "/map"