global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false
  width: 10.0
  height: 10.0
  resolution: 0.1  # 從 0.05 改為 0.1
  transform_tolerance: 1.0
  map_type: costmap

  plugins:
  - {name: static_layer,   type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}  # 啟用
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}  # 啟用

GlobalPlanner:
  allow_unknown: true  # 從 false 改為 true
  default_tolerance: 0.5
